### ISSUE TITLE
WTEventAction  -executeWithContext: 有些邪门

### ISSUE THREAD

**Issue by PerfectShen** [hongruqi/WTModule#1]
[截图看这里](https://github.com/PerfectShen/WTModule/blob/master/检测.png)
在切到另外一个线程去进行消息发送时`WTEventItem`会被释放，`WTEventContext`所指向的`event`也变为nil，在`WTAXXModule` 的 `- userLogin:`中无法获取到传过来的参数

**Comment by hongruqi** [comment]
多线程。导致weak 属性被释放。



At 2018-04-25 16:55:29, "Seeulater" <notifications@github.com> wrote:


截图看这里
在切到另外一个线程去进行消息发送时WTEventItem会被释放，WTEventContext所指向的event也变为nil，在WTAXXModule 的 - userLogin:中无法获取到传过来的参数

**Comment by PerfectShen** [comment]
我修改了一下这块的处理，你看一下我改的对不对。

**Comment by PerfectShen** [comment]
还有一个问题就是 你们现在组件化的是这框架吗，如果这个地方有问题 那在实际开发中肯定会发现的。
有一点我很赞同的是，对于模块之间通信，B提供了什么，A才能去访问什么。
“通过上面的定义，我们会发现路由协议不适用于我们对组件的定义。 分析：页面路由，打破了件间的独立性，虽然是通过统一的协议进行访问。但是这样就存在一个问题。A组件的一个子界面，可以访问B组件的子界面。这对我们对组件的理解有些矛盾。A组件的子界面需要调用B的子界面，需要通过B组件提供的接口调用。” 通信方式的选择无非是为了不产生直接引用，target-action在这方面要优于基于字符串匹配的router。

**Comment by hongruqi** [comment]
@PerfectShen EventBus 这块没在项目中用。 EventBus 是仿照java 的eventbus 自己写的。有问题可以随时联系。

**Comment by hongruqi** [comment]
你怎么改的，可以提一个merger request 过来。

**Comment by hongruqi** [comment]
你可以加我 微信： 15267031755

**Comment by PerfectShen** [comment]
提了 一个pull request 你看一下
